### ISSUE TITLE
How to run contrastive evaluation on BIG-PAR?

### ISSUE THREAD

**Issue by zihanlalala** [neulab/contextual-mt#13]
Dear author,

I am trying to run contrastive evaluation on BIG-PAR, but I only find ContraPro and bawden choices in file docmt_contrastive_eval.py. Could you please provide a script to evaluate BIG-PAR?

Thank you.

**Comment by kayoyin** [comment]
Hello! 
You can download the `highlighted.test.*` files in `data/scat` which constitutes the BIG-PAR data. Then, you can run
```
python contextual_mt/docmt_contrastive_eval.py \
    --source-lang en --target-lang fr \
    --source-file $DATA_PATH/highlighted.test.en --src-context-file $DATA_PATH/highlighted.test.context.en \
    --target-file $DATA_PATH/highlighted.test.fr --tgt-context-file $DATA_PATH/highlighted.test.context.fr \
    --path $MODEL_CKPT --dataset bawden
```

**Comment by zihanlalala** [comment]
The script worked. Thanks!
